/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogsMacrociclo;

import entidades.Macrociclo;
import entidades.MedioFisico;
import interfaces.IPersistenciaFachada;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import negocio.PersistenciaFachada;

/**
 *
 * @author x11_r
 */
public class DlgSeleccionarMediosFisicos extends javax.swing.JFrame {

    IPersistenciaFachada persistencia;
    Macrociclo macrociclo;
    List<MedioFisico> mediosFisicos;
    String[] medios = new String[]{"RAG (KM)", "RAE (MIN)", "VEL.GENERAL(MTROS)", "VEL. ESPECIAL(SEG)", "RES. VEL.GEN(MTROS)", "RES.VEL.ESP(MIN)", "FUERZA. GEN(REP)", "FUERZA.ESP(REP)", "COORDINACION tecnica(REP)", "FLEXIBILIDAD(MIN)"};

    /**
     * Creates new form DlgSeleccionarMediosFisicos
     */
    public DlgSeleccionarMediosFisicos() {
        persistencia = PersistenciaFachada.getInstance();
        initComponents();

    }

    public DlgSeleccionarMediosFisicos(Macrociclo macrociclo) {
        persistencia = PersistenciaFachada.getInstance();
        mediosFisicos = new ArrayList<>(); // Inicializa la lista aquí

        initComponents();
        this.macrociclo = macrociclo;
        setLocationRelativeTo(null);
        setVisible(true);
        cargarMediosEnComboBox();
        TextFieldNombreMacro.setText(macrociclo.getNombre());
    }

    private void cargarMediosEnComboBox() {
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(medios);
        ComboBoxMedios.setModel(comboBoxModel);

    }

    private void guardarTodosLosMediosFisicos() {
        // Limpia la lista de mediosFisicos si ya contiene elementos

        // Itera a través de los elementos en el JComboBox y agrégalos a la lista mediosFisicos
        for (int i = 0; i < ComboBoxMedios.getItemCount(); i++) {
            String medioSeleccionado = (String) ComboBoxMedios.getItemAt(i);

            MedioFisico medioFisico = new MedioFisico();
            medioFisico.setNombre(medioSeleccionado);
            mediosFisicos.add(medioFisico);

        }
        System.out.println(mediosFisicos);
        macrociclo.setMediosFisicos(mediosFisicos);
        persistencia.actualizarMacrociclo(macrociclo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBoxMedios = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldNombreMacro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComboBoxMedios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxMedios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMediosActionPerformed(evt);
            }
        });

        jLabel1.setText("Medios Físicos");

        jLabel2.setText("Identificador del Macrociclo");

        TextFieldNombreMacro.setEditable(false);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldNombreMacro, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(ComboBoxMedios, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextFieldNombreMacro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxMedios, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxMediosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMediosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMediosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        guardarTodosLosMediosFisicos();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxMedios;
    private javax.swing.JTextField TextFieldNombreMacro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
